name: Build and Push Docker image

on:
  push:
    branches: [ main ]  # main 브랜치에 push가 발생하면 이 워크플로우가 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub-hosted runner, Ubuntu 최신 버전 사용

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2  # 리포지토리 코드를 체크아웃

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 유저네임, GitHub Secrets에서 설정
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 패스워드, GitHub Secrets에서 설정

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .  # Dockerfile이 있는 위치
        file: ./Dockerfile  # Dockerfile 경로
        push: true  # 이미지를 빌드 후 푸시
        tags: chan2slo/newsfeeder_bot:latest  # 이미지 태그 설정